<?php

namespace src\Applications\Http\Enum\ErrorCodes;

final class RoleErrorCode extends ErrorCodes
{
    const ERR_EMPTY_NAME          = 'ERR_EMPTY_NAME';
    const ERR_INVALID_NAME        = 'ERR_INVALID_EMPTY';
    const ERR_INVALID_SORT        = 'ERR_INVALID_SORT';
    const ERR_EMPTY_IDENTIFIER    = 'ERR_EMPTY_IDENTIFIER';
    const ERR_INVALID_IDENTIFIER  = 'ERR_INVALID_IDENTIFIER';
    const ERR_EMPTY_PERMISSIONS_FIELD   = 'ERR_EMPTY_PERMISSIONS_FIELD';
    const ERR_INVALID_PERMISSIONS_FIELD = 'ERR_INVALID_PERMISSIONS_FIELD';
    const ERR_EMPTY_PERMISSIONS_VALUE = 'ERR_EMPTY_PERMISSIONS_VALUE';
    const ERR_INDISTINCT_PERMISSIONS = 'ERR_INDISTINCT_PERMISSIONS';
    const ERR_INVALID_PERMISSIONS_VALUE = 'ERR_INVALID_PERMISSIONS_VALUE';
}
